# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
early_access: false
reviews:
    profile: "assertive"
    request_changes_workflow: true
    high_level_summary: true
    poem: true
    review_status: true
    collapse_walkthrough: false
    path_instructions:
        -   path: "**/*.php"
            instructions:
                "
                Review the PHP code for conformity with the Spryker coding standards, highlighting any deviations.
                Spryker coding standards mentioned here https://docs.spryker.com/docs/dg/dev/backend-development/back-end-development.html
                - The Business layer should Contains the entire business logic.
                    The Business layer should not use any database related classes, only Entity manager and repository is allowed.

                - The Persistence layer should Responsible for the database structure and connections to it—for example, for the data persistence.
                - The Communication layer should Enables the connection to the external providers.
                 "
        -   path: "**/*.transfer.xml"
            instructions:
                "All new transfers and properties should be marked  strict=\"true\", highlighting any deviations."
    auto_review:
        enabled: true
        ignore_title_keywords:
            - "WIP"
            - "DO NOT MERGE"
        drafts: false
chat:
    auto_reply: true
